export const functionHalls = [
  {
    id: 1,
    name: 'Banquet Hall in Collingwood',
    rating: 4.89,
    reviewsCount: 128,
    location: 'Collingwood, Ontario',
    description: 'A beautiful beach house ideal for family gatherings and small events.',
    imageUrl: 'https://i.pinimg.com/736x/56/66/a5/5666a5c9918aa056fa3c3abb2481c76b.jpg',
    price: 240000,
    capacity: 50,
    eventType: 'Weddings, Private Events',
    amenities: ['Parking', 'Beachfront', 'Wi-Fi'],
  },
  {
    id: 2,
    name: 'Elegant Grand Ballroom',
    rating: 4.75,
    reviewsCount: 200,
    location: 'Toronto, Ontario',
    description: 'A grand ballroom with luxurious decor, perfect for large events and galas.',
    imageUrl: 'https://i.pinimg.com/736x/07/62/1a/07621a921ac049c538aed4beec1b63dc.jpg',
    price: 500000,
    capacity: 300,
    eventType: 'Corporate Events, Weddings, Conferences',
    amenities: ['Parking', 'AV Equipment', 'Catering Service', 'Wi-Fi'],
  },
  {
    id: 3,
    name: 'Rustic Barn Venue',
    rating: 4.65,
    reviewsCount: 95,
    location: 'Niagara Falls, Ontario',
    description: 'A rustic barn offering a charming and unique setting for weddings and parties.',
    imageUrl: 'https://i.pinimg.com/736x/2b/dc/58/2bdc58a57bbd307686287d3264e7268a.jpg',
    price: 320000,
    capacity: 150,
    eventType: 'Weddings, Receptions, Private Events',
    amenities: ['Parking', 'Outdoor Space', 'Wi-Fi'],
  },
  {
    id: 4,
    name: 'City Center Conference Hall',
    rating: 4.80,
    reviewsCount: 250,
    location: 'Vancouver, British Columbia',
    description: 'State-of-the-art conference hall suitable for large corporate meetings and seminars.',
    imageUrl: 'https://i.pinimg.com/736x/ee/a7/fa/eea7fa2348c520dff2a0604f1a812cd1.jpg',
    price: 450000,
    capacity: 400,
    eventType: 'Conferences, Receptions',
    amenities: ['AV Equipment', 'Wi-Fi', 'Catering Service', 'Parking'],
  },
  {
    id: 5,
    name: 'Luxury Penthouse Event Space',
    rating: 4.90,
    reviewsCount: 78,
    location: 'Montreal, Quebec',
    description: 'A luxurious penthouse with breathtaking city views, perfect for upscale events.',
    imageUrl: 'https://i.pinimg.com/736x/06/10/12/0610125d5a122c10116c29716c0e5a78.jpg',
    price: 600000,
    capacity: 100,
    eventType: 'Private Events, Product Launches',
    amenities: ['City View', 'Wi-Fi', 'Valet Parking'],
  },
  {
    id: 6,
    name: 'Vintage Garden Hall',
    rating: 4.80,
    reviewsCount: 110,
    location: 'Ottawa, Ontario',
    description: 'A charming garden hall with a vintage feel, perfect for weddings and garden parties.',
    imageUrl: 'https://i.pinimg.com/736x/34/37/45/3437459cd06e55f1f0121f2600c29e85.jpg',
    price: 350000,
    capacity: 180,
    eventType: 'Weddings, Receptions',
    amenities: ['Outdoor Garden', 'Wi-Fi', 'Catering'],
  },
  {
    id: 7,
    name: 'Modern Art Gallery Hall',
    rating: 4.75,
    reviewsCount: 150,
    location: 'Calgary, Alberta',
    description: 'A stylish hall in an art gallery, ideal for corporate events and cocktail parties.',
    imageUrl: 'https://i.pinimg.com/736x/07/d5/32/07d532ca328e2b2d44d1feba47c3e14c.jpg',
    price: 450000,
    capacity: 200,
    eventType: 'Corporate Events, Product Launches',
    amenities: ['AV Equipment', 'Wi-Fi', 'Catering'],
  },
  {
    id: 8,
    name: 'Elegant Lakeside Pavilion',
    rating: 4.85,
    reviewsCount: 130,
    location: 'Kelowna, British Columbia',
    description: 'A beautiful lakeside pavilion offering a scenic backdrop for weddings and receptions.',
    imageUrl: 'https://i.pinimg.com/736x/ab/67/d8/ab67d85281efd5b70be25c47f93b4b58.jpg',
    price: 375000,
    capacity: 250,
    eventType: 'Weddings, Receptions, Private Events',
    amenities: ['Lakeside View', 'Parking', 'Wi-Fi'],
  },
  {
    id: 9,
    name: 'Cozy Boutique Venue',
    rating: 4.70,
    reviewsCount: 60,
    location: 'Hamilton, Ontario',
    description: 'A boutique venue for intimate gatherings, perfect for small weddings and events.',
    imageUrl: 'https://i.pinimg.com/736x/ed/be/25/edbe25b54256439d445e5a879930ce55.jpg',
    price: 275000,
    capacity: 70,
    eventType: 'Weddings, Corporate Parties',
    amenities: ['Wi-Fi', 'Air Conditioning'],
  },
  {
    id: 10,
    name: 'Historic Castle Venue',
    rating: 4.93,
    reviewsCount: 98,
    location: 'Quebec City, Quebec',
    description: 'An ancient castle with an elegant ballroom, ideal for high-end events and weddings.',
    imageUrl: 'https://i.pinimg.com/736x/85/c0/5e/85c05e33146f60da2e57fa5c2acefa66.jpg',
    price: 700000,
    capacity: 350,
    eventType: 'Weddings, Corporate Events',
    amenities: ['Ballroom', 'Wi-Fi', 'Catering'],
  },
  {
    id: 11,
    name: 'Mountain Lodge Retreat',
    rating: 4.80,
    reviewsCount: 120,
    location: 'Whistler, British Columbia',
    description: 'A serene mountain lodge, perfect for retreats and outdoor weddings.',
    imageUrl: 'https://i.pinimg.com/736x/87/8c/53/878c53b266136ce007b6c6c0adcc5a64.jpg',
    price: 400000,
    capacity: 150,
    eventType: 'Weddings, Conferences',
    amenities: ['Mountain View', 'Wi-Fi', 'Outdoor Space'],
  },
  {
    id: 12,
    name: 'Modern Loft Event Space',
    rating: 4.85,
    reviewsCount: 140,
    location: 'Toronto, Ontario',
    description: 'A sleek and modern loft for events, parties, and photo shoots.',
    imageUrl: 'https://i.pinimg.com/736x/a9/09/c1/a909c1521f8e24b974184bdd1b257b30.jpg',
    price: 325000,
    capacity: 100,
    eventType: 'Parties, Product Launches',
    amenities: ['Wi-Fi', 'Air Conditioning', 'Catering'],
  },
];
