export const sportsFacilities = [
  {
    id: 1,
    name: 'Olympic Sports Complex',
    rating: 4.9,
    reviewsCount: 200,
    location: 'Toronto, Ontario',
    description: 'A state-of-the-art sports complex with multiple facilities for athletics, swimming, and indoor games.',
    imageUrl: 'https://i.pinimg.com/736x/21/96/c1/2196c1b2d8c9af7929674c7abd4eb94f.jpg',
    price: 500000,
    capacity: 1000,
    sports: 'Swimming, Basketball',
    amenities: ['Indoor Courts', 'Olympic Pool', 'Fitness Center', 'Parking'],
  },
  {
    id: 2,
    name: 'Urban Soccer Arena',
    rating: 4.7,
    reviewsCount: 150,
    location: 'Vancouver, British Columbia',
    description: 'An indoor soccer arena with high-quality turf and amenities for players and spectators.',
    imageUrl: 'https://i.pinimg.com/736x/dc/b5/2b/dcb52b008f70932b7de44ae1e2ae0518.jpg',
    price: 300000,
    capacity: 300,
    sports: 'Soccer, Futsal',
    amenities: ['Turf Field', 'Changing Rooms', 'Snack Bar', 'Wi-Fi'],
  },
  {
    id: 3,
    name: 'Peak Climbing Gym',
    rating: 4.8,
    reviewsCount: 180,
    location: 'Montreal, Quebec',
    description: 'A modern indoor climbing gym with climbing walls for beginners to advanced climbers.',
    imageUrl: 'https://i.pinimg.com/736x/9f/1b/8a/9f1b8a3a24c760451a9cf6265930c43f.jpg',
    price: 200000,
    capacity: 150,
    sports: 'Futsal',
    amenities: ['Climbing Gear Rental', 'Training Area', 'Café'],
  },
  {
    id: 4,
    name: 'Elite Tennis Club',
    rating: 4.85,
    reviewsCount: 210,
    location: 'Whistler, Columbia',
    description: 'A premier tennis club with both indoor and outdoor courts, coaching facilities, and a pro shop.',
    imageUrl: 'https://i.pinimg.com/236x/9e/9d/f2/9e9df2c5a18ead3d008c537b22372af3.jpg',
    price: 350000,
    capacity: 200,
    sports: 'Tennis, Table Tennis',
    amenities: ['Indoor Courts', 'Outdoor Courts', 'Pro Shop', 'Wi-Fi'],
  },
  {
    id: 5,
    name: 'Skate & Ice Arena',
    rating: 4.9,
    reviewsCount: 140,
    location: 'Calgary, Alberta',
    description: 'A full-size ice skating and hockey arena with training facilities for skaters of all levels.',
    imageUrl: 'https://i.pinimg.com/736x/4f/d3/9b/4fd39b8cd705f94282b355e68474c2dc.jpg',
    price: 400000,
    capacity: 400,
    sports: 'Ice Skating',
    amenities: ['Skate Rentals', 'Changing Rooms', 'Spectator Seating'],
  },
  {
    id: 6,
    name: 'Mountain Biking Trails Center',
    rating: 4.7,
    reviewsCount: 100,
    location: 'Banff, Alberta',
    description: 'Extensive trails for mountain biking enthusiasts, ranging from beginner to expert levels.',
    imageUrl: 'https://images.unsplash.com/photo-1527181152855-928b0b18b1f4?crop=entropy&cs=tinysrgb&fit=max&q=80&w=1080',
    price: 150000,
    capacity: 100,
    sports: 'Ice Skating',
    amenities: ['Trail Map Service', 'Bike Rentals', 'First Aid Station'],
  },
  {
    id: 7,
    name: 'Community Swimming Pool',
    rating: 4.6,
    reviewsCount: 120,
    location: 'Ottawa, Ontario',
    description: 'A public swimming facility with both lap pools and recreational pools for children and adults.',
    imageUrl: 'https://images.unsplash.com/photo-1578496781985-e1b7a9f3fd20?crop=entropy&cs=tinysrgb&fit=max&q=80&w=1080',
    price: 180000,
    capacity: 300,
    sports: 'Swimming',
    amenities: ['Locker Rooms', 'Children’s Pool', 'Lifeguard Service'],
  },
  {
    id: 8,
    name: 'CrossFit Training Center',
    rating: 4.75,
    reviewsCount: 95,
    location: 'Edmonton, Alberta',
    description: 'An intense CrossFit training center with expert trainers and high-end fitness equipment.',
    imageUrl: 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?crop=entropy&cs=tinysrgb&fit=max&q=80&w=1080',
    price: 250000,
    capacity: 100,
    sports: 'Swimming',
    amenities: ['Personal Trainers', 'Weights & Machines', 'Shower Facilities'],
  },
  {
    id: 9,
    name: 'Highland Golf Course',
    rating: 4.8,
    reviewsCount: 75,
    location: 'Halifax, Nova Scotia',
    description: 'A scenic golf course offering challenging terrain and breathtaking views for golf enthusiasts.',
    imageUrl: 'https://images.unsplash.com/photo-1584481577035-0d7a4c3764cd?crop=entropy&cs=tinysrgb&fit=max&q=80&w=1080',
    price: 450000,
    capacity: 250,
    sports: 'Golf',
    amenities: ['Golf Cart Rentals', 'Clubhouse', 'Pro Shop'],
  },
  {
    id: 10,
    name: 'Indoor Badminton Arena',
    rating: 4.7,
    reviewsCount: 90,
    location: 'Victoria, British Columbia',
    description: 'A large indoor facility dedicated to badminton players of all skill levels.',
    imageUrl: 'https://images.unsplash.com/photo-1596464716122-88ab3cbe0bc4?crop=entropy&cs=tinysrgb&fit=max&q=80&w=1080',
    price: 230000,
    capacity: 150,
    sports: 'Badminton',
    amenities: ['Indoor Courts', 'Equipment Rentals', 'Cafeteria'],
  },
];
