export const wellnessServices = [
    {
        id: 1,
        name: 'Luxury Spa Retreat',
        rating: 4.9,
        reviewsCount: 150,
        location: 'Banff, Alberta',
        description: 'An exclusive spa retreat offering luxury treatments and breathtaking mountain views.',
        imageUrl: 'https://i.pinimg.com/736x/4c/96/87/4c9687fe28278fa30e1e77df99d20a48.jpg',
        price: 12000,
        capacity: 20,
        services: 'Spa Treatments, Massage Therapy',
        amenities: ['Mountain View', 'Sauna', 'Fitness Center'],
    },
    {
        id: 2,
        name: 'Yoga and Wellness Center',
        rating: 4.8,
        reviewsCount: 90,
        location: 'Vancouver, British Columbia',
        description: 'A serene wellness center offering yoga classes, meditation workshops, and wellness therapies.',
        imageUrl: 'https://i.pinimg.com/736x/34/d5/73/34d573db558016ba3f033c8c32ede09b.jpg',
        price: 8000,
        capacity: 50,
        services: 'Yoga Classes, Meditation',
        amenities: ['Yoga Studio', 'Outdoor Garden', 'Tea Lounge'],
    },
    {
        id: 3,
        name: 'Holistic Health Spa',
        rating: 4.75,
        reviewsCount: 110,
        location: 'Toronto, Ontario',
        description: 'A holistic spa offering treatments focused on body, mind, and spirit rejuvenation.',
        imageUrl: 'https://i.pinimg.com/736x/08/10/5d/08105d5627c3d5b3bb2e00d2ab5592fa.jpg',
        price: 15000,
        capacity: 30,
        services: 'Spa Treatments',
        amenities: ['Wellness Library', 'Steam Room', 'Café'],
    },
    {
        id: 4,
        name: 'Rejuvenation Therapy Center',
        rating: 4.85,
        reviewsCount: 180,
        location: 'Montreal, Quebec',
        description: 'A modern therapy center specializing in rejuvenation therapies and rehabilitation services.',
        imageUrl: 'https://i.pinimg.com/736x/f0/95/4d/f0954d74dc6cafb434334c2bb502e6bd.jpg',
        price: 18000,
        capacity: 40,
        services: 'Rehabilitation Services',
        amenities: ['Rehab Equipment', 'Therapy Pool', 'Private Consultation Rooms'],
    },
    {
        id: 5,
        name: 'Zen Wellness Sanctuary',
        rating: 4.92,
        reviewsCount: 200,
        location: 'Calgary, Alberta',
        description: 'A sanctuary offering Zen-inspired wellness services to relax and rejuvenate.',
        imageUrl: 'https://i.pinimg.com/736x/90/97/41/9097415bdd49fc486c9e8396f9ed833d.jpg',
        price: 14000,
        capacity: 25,
        services: 'Meditation',
        amenities: ['Zen Garden', 'Meditation Hall', 'Herbal Tea Bar'],
    },
    {
        id: 6,
        name: 'Detox and Wellness Spa',
        rating: 4.7,
        reviewsCount: 130,
        location: 'Ottawa, Ontario',
        description: 'A wellness spa specializing in detox programs, weight management, and nutrition coaching.',
        imageUrl: 'https://i.pinimg.com/736x/8c/9f/a7/8c9fa7dbc6e87d9a2d83c5bf0acf7874.jpg',
        price: 20000,
        capacity: 35,
        services: 'Spa Treatments',
        amenities: ['Detox Juice Bar', 'Infrared Sauna', 'Fitness Studio'],
    },
    {
        id: 7,
        name: 'Healing Touch Wellness Center',
        rating: 4.88,
        reviewsCount: 75,
        location: 'Hamilton, Ontario',
        description: 'A holistic wellness center providing massage therapy, energy healing, and relaxation sessions.',
        imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?crop=entropy&cs=tinysrgb&fit=max&ixid=MXwyMDg5N3wwfHx8fHx8fHx8fHw&ixlib=rb-1.2.1&q=80&w=1080',
        price: 9500,
        capacity: 15,
        services: 'Massage Therapy',
        amenities: ['Relaxation Lounge', 'Private Therapy Rooms', 'Aromatherapy Diffusers'],
    },
    {
        id: 8,
        name: 'Tranquil Oasis Spa',
        rating: 4.9,
        reviewsCount: 85,
        location: 'Niagara-on-the-Lake, Ontario',
        description: 'A serene spa offering tranquility, relaxation, and specialized massage treatments.',
        imageUrl: 'https://i.pinimg.com/736x/54/08/cf/5408cf7c931758a062b84ab4603f1ea3.jpg',
        price: 12000,
        capacity: 20,
        services: 'Massage Therapy, Facial Treatments',
        amenities: ['Hot Tub', 'Outdoor Deck', 'Steam Room'],
    },
    {
        id: 9,
        name: 'Herbal Healing Center',
        rating: 4.83,
        reviewsCount: 65,
        location: 'Quebec City, Quebec',
        description: 'An herbal healing center offering natural remedies, holistic therapies, and wellness coaching.',
        imageUrl: 'https://images.unsplash.com/photo-1526045612212-70caf35c14df?crop=entropy&cs=tinysrgb&fit=max&ixid=MXwyMDg5N3wwfHx8fHx8fHx8fHw&ixlib=rb-1.2.1&q=80&w=1080',
        price: 10000,
        capacity: 20,
        services: 'Counseling',
        amenities: ['Herbal Shop', 'Consultation Rooms', 'Relaxation Garden'],
    },
    {
        id: 10,
        name: 'Rejuvenate Wellness Spa',
        rating: 4.86,
        reviewsCount: 140,
        location: 'Toronto, Ontario',
        description: 'A wellness spa dedicated to rejuvenating body and mind through a range of treatments.',
        imageUrl: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?crop=entropy&cs=tinysrgb&fit=max&ixid=MXwyMDg5N3wwfHx8fHx8fHx8fHw&ixlib=rb-1.2.1&q=80&w=1080',
        price: 15500,
        capacity: 40,
        services: 'Massage Therapy, Facial Treatments',
        amenities: ['Wellness Pool', 'Juice Bar', 'Private Cabanas'],
    },
];
